const PC = {
	INIT_MOVIES_QUANITY: 12,
	MOVIES_ON_ROW: 3,
};
const TABLET = {
	INIT_MOVIES_QUANITY: 8,
	MOVIES_ON_ROW: 2,
};
const MOBILE = {
	INIT_MOVIES_QUANITY: 5,
	MOVIES_ON_ROW: 2,
};

const SHORT_MOVIES_LENGTH = 40;

export { PC, TABLET, MOBILE, SHORT_MOVIES_LENGTH };