const PAGINATION_CONFIG = {
	DESKTOP: {
		INIT_MOVIES_QUANITY: 12,
		MOVIES_ON_ROW: 3,
	},
	TABLET: {
		INIT_MOVIES_QUANITY: 8,
		MOVIES_ON_ROW: 2,
	},
	MOBILE: {
		INIT_MOVIES_QUANITY: 5,
		MOVIES_ON_ROW: 2,
	},
}

const SHORT_MOVIES_LENGTH = 40;
const MIN_DESKTOP_WIDTH = 932;
const MIN_TABLET_WIDTH = 648;

export { PAGINATION_CONFIG, MIN_DESKTOP_WIDTH, MIN_TABLET_WIDTH, SHORT_MOVIES_LENGTH };