const PAGINATION_CONFIG = {
	PC: {
		INIT_MOVIES_QUANITY: 12,
		MOVIES_ON_ROW: 3,
	},
	TABLET: {
		INIT_MOVIES_QUANITY: 8,
		MOVIES_ON_ROW: 2,
	},
	MOBILE: {
		INIT_MOVIES_QUANITY: 5,
		MOVIES_ON_ROW: 2,
	},
}

const SHORT_MOVIES_LENGTH = 40;

export { PAGINATION_CONFIG, SHORT_MOVIES_LENGTH };